name: Go Build and Test

on:
  push: 
    branches:
    - 'main'
    
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.22.2"

      - name: Install dependencies
        run: go get . && go mod tidy

      - name: Build the code
        run: go build -v ./...

      - name: Run tests
        run: go test -v ./...